# Generated by Django 5.2.1 on 2025-06-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marcenaria_app", "0002_categoria_produto_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="destaque",
            field=models.BooleanField(default=False),
        ),
    ]
