# Generated by Django 5.2.1 on 2025-06-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marcenaria_app", "0003_produto_destaque"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produtocarrossel",
            name="carrossel",
        ),
        migrations.RemoveField(
            model_name="produtocarrossel",
            name="produto",
        ),
        migrations.DeleteModel(
            name="Carrossel",
        ),
        migrations.DeleteModel(
            name="ProdutoCarrossel",
        ),
    ]
