# Generated by Django 5.2.1 on 2025-07-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marcenaria_app", "0004_remove_produtocarrossel_carrossel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pagina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="pagina/")),
            ],
        ),
    ]
