# Generated by Django 5.2.1 on 2025-08-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marcenaria_app", "0005_pagina"),
    ]

    operations = [
        migrations.AddField(
            model_name="secao",
            name="imagem_centro",
            field=models.ImageField(blank=True, null=True, upload_to="secoes/"),
        ),
    ]
