# Generated by Django 5.2.1 on 2025-08-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marcenaria_app", "0006_secao_imagem_centro"),
    ]

    operations = [
        migrations.CreateModel(
            name="Galeria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="secoes/"),
                ),
            ],
        ),
    ]
